---
    - name: UPDATE
      apt: update_cache=yes

    - name: DEPENDENCIES
      apt: name={{ item }}
      with_items:

          - libpq-dev
          - python-psycopg2
          - postgresql
          - postgresql-contrib
          - pgadmin3

    - name: Add PostgreSQL repo key
      apt_key: url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc

    - name: Add PostgreSQL repo
      apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main'

    - name: CREATE DATABASE
      sudo_user: postgres
      postgresql_db: name=sample state=present

    - name: CREATE USER
      sudo_user: postgres
      postgresql_user: db=sample name=ravi password=12345 state=present 

    - name: DELETE USER
      sudo_user: postgres
      postgresql_user: db=sample name=ravi state=absent 

    - name: DELETE DATABASE
      sudo_user: postgres
      postgresql_db: name=sample state=absent