---
    - name: UPDATE
      apt: update_cache=yes

    - name: DEPENDENCIES
      apt: name={{ item }}
      with_items:

          - libpcre3 
          - libpcre3-dev

    - name: DOWNLOADING THE UPDATED VERSION OF NGINX
      unarchive: src=http://nginx.org/download/nginx-{{ nginx_version }}.tar.gz dest=/tmp/ copy=no

    - name: TO CONFIGURE NGINX
      shell: "{{ item }}"
      args:
        chdir: /tmp/nginx-{{ nginx_version }}
      with_items:

          - ./configure
          - make
          - make install

    - name: COPY NGINX CONFIGURATION FILE
      template:
       src: nginx.conf.j2
       dest: /etc/nginx/nginx.conf
      notify: restart nginx

    - name: ENSURE NGINX IS RESTARTED AND ENABLED TO START BOOT
      service: name=nginx state=started enabled=yes
