---
    - name: UPDATE
      apt: update_cache=yes

    - name: DEPENDENCIES
      apt: name={{ item }}
      with_items:

         - autotools-dev
         - debhelper 
         - dpkg-dev 
         - gawk
         - libapr1-dev 
         - libaprutil1-dev 
         - libcap-dev
         - liblua5.2-dev
         - libpcre3-dev
         - libssl-dev 
         - libxml2-dev
         - lsb-release
         - perl
         - zlib1g-dev

    - name: DOWNLOADING UPDATED VERSION OF APACHE2
      unarchive: src=https://launchpad.net/ubuntu/+archive/primary/+files/apache2_{{ apache2_version }}.orig.tar.bz2 dest=/tmp/ copy=no

    - name: TO CONFIGURE APACHE2
      shell: "{{ item }}"
      args:
        chdir: /tmp/httpd-{{ apache2_version }}
      with_items:

             - ./configure
             - make
             - make install

   