---
    - name: UPDATE
      apt: update_cache=yes

    - name: DEPENDENCIES
      apt: name={{ item }}
      with_items:

          - build-essential
          - openssl
          - libssl-dev
          - pkg-config 

    - name: DOWNLOADING UPDATED VERSION OF NODEJS 
      unarchive: src=http://nodejs.org/dist/{{ nodejs_version }}/node-{{ nodejs_version }}.tar.gz dest=/tmp/ copy=no

    - name: TO CONFIGURE NODEJS
      shell: "{{ item }}"
      args:
        chdir: /tmp/node-{{ nodejs_version }}
      with_items:

             - ./configure
             - make
             - make install